### PR TITLE
Vmas

### PR DESCRIPTION
**Pull request by mdwyman**
Added db files, example substitutions file, example iocsh file, and UI screens for variable mask aperture slits (white beam slits) being installed of upgrade

### CODE REVIEW

**Review by kmpeters — COMMENTED** [review]
The ``.loglogin`` file should be deleted.

Should the ``xxx:`` references in *vmas.iocsh* be replaced with ``$(PREFIX)``?  This is probably a question for @keenanlang.

**Comment by prjemian** [comment]
> @mdwyman, the `.loglogin` file should be deleted.
> 
> Should the `xxx:` references in **vmas.iocsh** be replaced with `$(PREFIX)`? This is probably a question for @keenanlang.

For example: https://github.com/BCDA-APS/apstools/blob/c36b881bc1ba1e5c1b893f26c1921ca7ae1603e6/.gitignore#L31-L33

**Comment by mdwyman** [comment]
@kmpeters Took out .loglogin (updated .gitignore as @prjemian suggested) and since I was already using macros for the motors in the example, I went ahead and swapped out the xxx: for $(P).

**Comment by kmpeters** [comment]
@mdwyman, it looks good to me.  Are there any more changes you want to make to this PR before I merge it?

**Pull request merged**
