### PR TITLE
Callable iocsh scripts

### PR DESCRIPTION
**Pull request by keenanlang**
Added iocsh files for all support that require more than just a database.

### CODE REVIEW

**Comment by anjohnson** [comment]
Is the extension `.iocsh` already in common use? I would prefer `.cmd` if you're only just starting out, since it matches the long-standing `st.cmd` filenames that we've always used.

**Comment by prjemian** [comment]
Is that sufficient to differentiate it from the existing shell script we use now?  Or is it really the same shell?

**Comment by anjohnson** [comment]
From Keenan's examples in this commit it looks like the same shell, but I don't know for sure what you guys have been doing. The iocsh language was designed to be as closely compatible with the VxWorks shell as Eric could reasonably make it.

**Comment by keenanlang** [comment]
.iocsh has been used by both Tim Mooney and Mark Rivers to denote command files that must be interpreted by iocsh rather than vxWorks; usually to get around line-length limits.

**Comment by anjohnson** [comment]
@keenanlang Ok, that sounds like a good-enough reason!

**Pull request merged**
