### PR TITLE
Unit test fix (mostly)

### PR DESCRIPTION
**Pull request by kmpeters**
Fix for most of the travis build errors due to unit tests.  Windows shared builds still fail.

### CODE REVIEW

**Comment by MarkRivers** [comment]
I can easily build the master branch of optics on Windows dynamic and static.  Do you want me to fix these issues and push to a branch on Github?

**Comment by MarkRivers** [comment]
Sorry, I accidentally pushed to master rather than a branch.  I fixed many of the problems, only the SNL program is failing now.  I'll fix it.

**Comment by MarkRivers** [comment]
I have fixed the master branch so the dynamic Windows build now succeeds on Travis.

**Comment by kmpeters** [comment]
Thanks Mark!

**Pull request closed without merging**
